//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidBot.Protocol.DataCenter
{
    using System.Collections.Generic;
    using RaidBot.Common.IO;
    using System;


    [Serializable()]
    public class EffectInstance : IData
    {

        public virtual uint EffectUid
        {
            get
            {
                return mEffectUid;
            }
            set
            {
                mEffectUid = value;
            }
        }

        private uint mEffectUid;

        public virtual uint EffectId
        {
            get
            {
                return mEffectId;
            }
            set
            {
                mEffectId = value;
            }
        }

        private uint mEffectId;

        public virtual int TargetId
        {
            get
            {
                return mTargetId;
            }
            set
            {
                mTargetId = value;
            }
        }

        private int mTargetId;

        public virtual string TargetMask
        {
            get
            {
                return mTargetMask;
            }
            set
            {
                mTargetMask = value;
            }
        }

        private string mTargetMask;

        public virtual int Duration
        {
            get
            {
                return mDuration;
            }
            set
            {
                mDuration = value;
            }
        }

        private int mDuration;

        public virtual int Delay
        {
            get
            {
                return mDelay;
            }
            set
            {
                mDelay = value;
            }
        }

        private int mDelay;

        public virtual int Random
        {
            get
            {
                return mRandom;
            }
            set
            {
                mRandom = value;
            }
        }

        private int mRandom;

        public virtual int Group
        {
            get
            {
                return mGroup;
            }
            set
            {
                mGroup = value;
            }
        }

        private int mGroup;

        public virtual int Modificator
        {
            get
            {
                return mModificator;
            }
            set
            {
                mModificator = value;
            }
        }

        private int mModificator;

        public virtual bool Trigger
        {
            get
            {
                return mTrigger;
            }
            set
            {
                mTrigger = value;
            }
        }

        private bool mTrigger;

        public virtual string Triggers
        {
            get
            {
                return mTriggers;
            }
            set
            {
                mTriggers = value;
            }
        }

        private string mTriggers;


        public virtual bool VisibleInTooltip
        {
            get
            {
                return mVisibleInTooltip;
            }
            set
            {
                mVisibleInTooltip = value;
            }
        }

        private bool mVisibleInTooltip;


        public virtual bool VisibleInBuffUi
        {
            get
            {
                return mVisibleInBuffUi;
            }
            set
            {
                mVisibleInBuffUi = value;
            }
        }

        private bool mVisibleInBuffUi;


        public virtual bool VisibleInFightLog
        {
            get
            {
                return mVisibleInFightLog;
            }
            set
            {
                mVisibleInFightLog = value;
            }
        }

        private bool mVisibleInFightLog;



        public virtual Object ZoneSize
        {
            get
            {
                return mZoneSize;
            }
            set
            {
                mZoneSize = value;
            }
        }

        private Object mZoneSize;

        public virtual uint ZoneShape
        {
            get
            {
                return mZoneShape;
            }
            set
            {
                mZoneShape = value;
            }
        }

        private uint mZoneShape;

        public virtual Object ZoneMinSize
        {
            get
            {
                return mZoneMinSize;
            }
            set
            {
                mZoneMinSize = value;
            }
        }

        private Object mZoneMinSize;

        public virtual Object ZoneEfficiencyPercent
        {
            get
            {
                return mZoneEfficiencyPercent;
            }
            set
            {
                mZoneEfficiencyPercent = value;
            }
        }

        private Object mZoneEfficiencyPercent;

        public virtual Object ZoneMaxEfficiency
        {
            get
            {
                return mZoneMaxEfficiency;
            }
            set
            {
                mZoneMaxEfficiency = value;
            }
        }

        private Object mZoneMaxEfficiency;

        public Object ZomeStopAtTarget
        {
            get
            {
                return mZoneStopAtTarget;
            }
            set { mZoneStopAtTarget = value; }
        }

        private Object mZoneStopAtTarget;

        public int EffetElement
        {
            get { return mEffectElement; }
            set { mEffectElement = value; }
        }

        private int mEffectElement;

        public int SpellId
        {
            get { return mSpellId; }
            set { mSpellId = value; }
        }

        private int mSpellId;

        public EffectInstance()
        {
        }
    }
}
