//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidBot.Protocol.DataCenter
{
    using System.Collections.Generic;
    using RaidBot.Common.IO;
    using System;
    
    
    [Serializable()]
    public class QuestObjective : IData
    {
        
        public virtual uint Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private uint mId;
        
        public virtual uint StepId
        {
            get
            {
                return mStepId;
            }
            set
            {
                mStepId = value;
            }
        }
        
        private uint mStepId;
        
        public virtual uint TypeId
        {
            get
            {
                return mTypeId;
            }
            set
            {
                mTypeId = value;
            }
        }
        
        private uint mTypeId;
        
        public virtual int DialogId
        {
            get
            {
                return mDialogId;
            }
            set
            {
                mDialogId = value;
            }
        }
        
        private int mDialogId;
        
        public virtual List<uint> Parameters
        {
            get
            {
                return mParameters;
            }
            set
            {
                mParameters = value;
            }
        }
        
        private List<uint> mParameters = new List<uint>();
        
        public virtual Point Coords
        {
            get
            {
                return mCoords;
            }
            set
            {
                mCoords = value;
            }
        }
        
        private Point mCoords;
        
        public virtual int MapId
        {
            get
            {
                return mMapId;
            }
            set
            {
                mMapId = value;
            }
        }
        
        private int mMapId;
        
        public QuestObjective()
        {
        }
    }
}
