//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidBot.Protocol.DataCenter
{
    using System.Collections.Generic;
    using RaidBot.Common.IO;
    using System;
    
    
    [Serializable()]
    public class Document : IData
    {
        
        public virtual int Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private int mId;
        
        public virtual uint TypeId
        {
            get
            {
                return mTypeId;
            }
            set
            {
                mTypeId = value;
            }
        }
        
        private uint mTypeId;
        
        public virtual uint TitleId
        {
            get
            {
                return mTitleId;
            }
            set
            {
                mTitleId = value;
            }
        }
        
        private uint mTitleId;
        
        public virtual uint AuthorId
        {
            get
            {
                return mAuthorId;
            }
            set
            {
                mAuthorId = value;
            }
        }
        
        private uint mAuthorId;
        
        public virtual uint SubTitleId
        {
            get
            {
                return mSubTitleId;
            }
            set
            {
                mSubTitleId = value;
            }
        }
        
        private uint mSubTitleId;
        
        public virtual uint ContentId
        {
            get
            {
                return mContentId;
            }
            set
            {
                mContentId = value;
            }
        }
        
        private uint mContentId;
        
        public virtual string ContentCSS
        {
            get
            {
                return mContentCSS;
            }
            set
            {
                mContentCSS = value;
            }
        }
        
        private string mContentCSS;
        
        public Document()
        {
        }
    }
}
