//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidBot.Engine.Setting {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    public sealed partial class RemoteSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static RemoteSetting defaultInstance = ((RemoteSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RemoteSetting())));
        
        public static RemoteSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5555")]
        public short LoginListenPort {
            get {
                return ((short)(this["LoginListenPort"]));
            }
            set {
                this["LoginListenPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("443")]
        public short GameListenPort {
            get {
                return ((short)(this["GameListenPort"]));
            }
            set {
                this["GameListenPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string GameListenAdress {
            get {
                return ((string)(this["GameListenAdress"]));
            }
            set {
                this["GameListenAdress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34.252.21.81")]
        public string LoginConnectionAdresse {
            get {
                return ((string)(this["LoginConnectionAdresse"]));
            }
            set {
                this["LoginConnectionAdresse"] = value;
            }
        }
    }
}
