//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidBot.Engine.Setting {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class TrajetSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static TrajetSetting defaultInstance = ((TrajetSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TrajetSetting())));
        
        public static TrajetSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int ChangMapTimeOut {
            get {
                return ((int)(this["ChangMapTimeOut"]));
            }
            set {
                this["ChangMapTimeOut"] = value;
            }
        }
    }
}
