//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidBot.Protocol.DataCenter
{
    using System.Collections.Generic;
    using RaidBot.Common.IO;
    using System;
    
    
    [Serializable()]
    public class EffectInstanceDice : EffectInstanceInteger, IData
    {
        
        public virtual uint DiceNum
        {
            get
            {
                return mDiceNum;
            }
            set
            {
                mDiceNum = value;
            }
        }
        
        private uint mDiceNum;
        
        public virtual uint DiceSide
        {
            get
            {
                return mDiceSide;
            }
            set
            {
                mDiceSide = value;
            }
        }
        
        private uint mDiceSide;
        
        public EffectInstanceDice()
        {
        }
    }
}
