//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidBot.Protocol.DataCenter
{
    using System.Collections.Generic;
    using RaidBot.Common.IO;
    using System;
    
    
    [Serializable()]
    public class MapReference : IData
    {
        
        public virtual int Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private int mId;
        
        public virtual uint MapId
        {
            get
            {
                return mMapId;
            }
            set
            {
                mMapId = value;
            }
        }
        
        private uint mMapId;
        
        public virtual int CellId
        {
            get
            {
                return mCellId;
            }
            set
            {
                mCellId = value;
            }
        }
        
        private int mCellId;
        
        public MapReference()
        {
        }
    }
}
