//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidBot.Protocol.DataCenter
{
    using System.Collections.Generic;
    using RaidBot.Common.IO;
    using System;
    
    
    [Serializable()]
    public class SpellState : IData
    {
        
        public virtual int Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private int mId;
        
        public virtual uint NameId
        {
            get
            {
                return mNameId;
            }
            set
            {
                mNameId = value;
            }
        }
        
        private uint mNameId;
        
        public virtual bool PreventsSpellCast
        {
            get
            {
                return mPreventsSpellCast;
            }
            set
            {
                mPreventsSpellCast = value;
            }
        }
        
        private bool mPreventsSpellCast;
        
        public virtual bool PreventsFight
        {
            get
            {
                return mPreventsFight;
            }
            set
            {
                mPreventsFight = value;
            }
        }
        
        private bool mPreventsFight;
        
        public virtual bool IsSilent
        {
            get
            {
                return mIsSilent;
            }
            set
            {
                mIsSilent = value;
            }
        }
        
        private bool mIsSilent;
        
        public virtual List<int> EffectsIds
        {
            get
            {
                return mEffectsIds;
            }
            set
            {
                mEffectsIds = value;
            }
        }
        
        private List<int> mEffectsIds = new List<int>();
        
        public SpellState()
        {
        }
    }
}
