//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidBot.Protocol.DataCenter
{
    using System.Collections.Generic;
    using RaidBot.Common.IO;
    using System;
    
    
    [Serializable()]
    public class ItemType : IData
    {
        
        public virtual int Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private int mId;
        
        public virtual uint NameId
        {
            get
            {
                return mNameId;
            }
            set
            {
                mNameId = value;
            }
        }
        
        private uint mNameId;
        
        public virtual uint SuperTypeId
        {
            get
            {
                return mSuperTypeId;
            }
            set
            {
                mSuperTypeId = value;
            }
        }
        
        private uint mSuperTypeId;
        
        public virtual bool Plural
        {
            get
            {
                return mPlural;
            }
            set
            {
                mPlural = value;
            }
        }
        
        private bool mPlural;
        
        public virtual uint Gender
        {
            get
            {
                return mGender;
            }
            set
            {
                mGender = value;
            }
        }
        
        private uint mGender;
        
        public virtual string RawZone
        {
            get
            {
                return mRawZone;
            }
            set
            {
                mRawZone = value;
            }
        }
        
        private string mRawZone;
        
        public virtual bool NeedUseConfirm
        {
            get
            {
                return mNeedUseConfirm;
            }
            set
            {
                mNeedUseConfirm = value;
            }
        }
        
        private bool mNeedUseConfirm;
        
        public virtual bool Mimickable
        {
            get
            {
                return mMimickable;
            }
            set
            {
                mMimickable = value;
            }
        }
        
        private bool mMimickable;
        
        public ItemType()
        {
        }
    }
}
