//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidBot.Data.IO.D2O {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class GameDataParam : global::System.Configuration.ApplicationSettingsBase {
        
        private static GameDataParam defaultInstance = ((GameDataParam)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GameDataParam())));
        
        public static GameDataParam Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data")]
        public string GameDataFolderPath {
            get {
                return ((string)(this["GameDataFolderPath"]));
            }
            set {
                this["GameDataFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data\\i18n.d2i")]
        public string I18nFilePath {
            get {
                return ((string)(this["I18nFilePath"]));
            }
            set {
                this["I18nFilePath"] = value;
            }
        }
    }
}
