//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidBot.Protocol.DataCenter
{
    using System.Collections.Generic;
    using RaidBot.Common.IO;
    using System;
    
    
    [Serializable()]
    public class SkinPosition : IData
    {
        
        public virtual uint Id
        {
            get
            {
                return mId;
            }
            set
            {
                mId = value;
            }
        }
        
        private uint mId;
        
        public virtual List<TransformData> Transformation
        {
            get
            {
                return mTransformation;
            }
            set
            {
                mTransformation = value;
            }
        }
        
        private List<TransformData> mTransformation = new List<TransformData>();
        
        public virtual List<String> Clip
        {
            get
            {
                return mClip;
            }
            set
            {
                mClip = value;
            }
        }
        
        private List<String> mClip = new List<String>();
        
        public virtual List<uint> Skin
        {
            get
            {
                return mSkin;
            }
            set
            {
                mSkin = value;
            }
        }
        
        private List<uint> mSkin = new List<uint>();
        
        public SkinPosition()
        {
        }
    }
}
